#spring:
#  application:
#    name: hello-client
#    
#server:
#  port: 8000
#    
#    
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8070/eureka/
#  instance:
#    hostname: localhost
#    